version: 2.1
workflows:
  version: 2
  compile_sass_and_push:
    jobs:
      - npmbuild_and_persist
      - pantheon/push:
          requires:
            - npmbuild_and_persist
          checkout: false
          pre-steps:
            - checkout
            - attach_workspace:
                at: .
            - run: npm install 
orbs:
  pantheon: pantheon-systems/pantheon@0.1.0
jobs:
  npmbuild_and_persist:
    docker:
      - image: 'node:10.15.3'
    steps:
      - checkout
      - run:
          name: install npm dependencies 
          command: npm install
      - run:
          name: run build
          command: npm run build
      - run:
          name: start app
          command: npm run start
      - persist_to_workspace:
          root: .
          paths:
            - /
