version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - npmbuild_and_run
      - pantheon/push:
          requires:
            - npmbuild_and_persist
          checkout: false
          pre-steps:
            - checkout
orbs:
  pantheon: pantheon-systems/pantheon@0.1.0
jobs:
  npmbuild_and_run:
    docker:
      - image: 'node:14.16.0'
    steps:
      - checkout
      - run:
          name: install npm dependencies 
          command: npm install
      - run:
          name: run build
          command: npm run build
      - run:
          name: start app
          command: npm run start
